language: node_js
branches:
  only:
    - master
node_js:
  - stable
cache: yarn
script:
  - yarn test
  - if [ $TRAVIS_BRANCH = 'master' ]; then yarn build; fi
after_script:
  - npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
