language: node_js
branches:
  only:
    - master
node_js:
  - stable
cache: npm
script:
  - npm test
  - test $TRAVIS_BRANCH = 'master' && npm run build
after_script:
  - npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
